// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Summon Software Labs.
//
// tests_digest.cpp - the SHA-256 core against the published FIPS 180-4 / NIST
// vectors, streaming equivalence, the hexadecimal Digest form, per-byte
// sensitivity and the documented endianness helpers.
//
// The one-million-character vector is generated by the test itself; no clock,
// no randomness and no external file is involved.

#include <array>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <string>
#include <string_view>
#include <vector>

#include "dccp/power_topology/digest.hpp"
#include "dccp/power_topology/limits.hpp"
#include "dccp/power_topology/result.hpp"
#include "test_framework.hpp"

namespace {

using namespace dccp::power_topology;

std::string bytes(std::initializer_list<unsigned> values) {
  std::string out;
  out.reserve(values.size());
  for (const unsigned value : values) {
    out.push_back(static_cast<char>(static_cast<unsigned char>(value)));
  }
  return out;
}

std::string hex_of(const std::array<std::uint8_t, Sha256::kDigestBytes>& digest) {
  return to_hex(std::string_view(reinterpret_cast<const char*>(digest.data()), digest.size()));
}

/// One-shot digest rendered as lowercase hex.
std::string sha256_hex(std::string_view data) { return digest_bytes(data).to_hex(); }

/// Digest of the same bytes fed to update() in fixed-size chunks.
std::string sha256_hex_chunked(std::string_view data, std::size_t chunk) {
  Sha256 hasher;
  std::size_t index = 0;
  while (index < data.size()) {
    const std::size_t take = data.size() - index < chunk ? data.size() - index : chunk;
    hasher.update(data.data() + index, take);
    index += take;
  }
  return hex_of(hasher.finish());
}

std::string bit_flipped(std::string raw, std::size_t index, unsigned char mask) {
  raw[index] = static_cast<char>(static_cast<unsigned char>(raw[index]) ^ mask);
  return raw;
}

const std::string kMessage448 = "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq";
const std::string kMessage896 =
    "abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu";

const char* const kEmptyHex = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
const char* const kAbcHex = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad";
const char* const kMessage448Hex = "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1";
const char* const kMessage896Hex = "cf5b16a778af8380036ce59e7b0492370b249b11e8f07a51afac45037afee9d1";
const char* const kMillionAHex = "cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0";

}  // namespace

// ===========================================================================
// Published vectors
// ===========================================================================

PT_TEST(digest, published_fips_vectors_one_shot) {
  PT_CHECK_EQ(sha256_hex(""), std::string(kEmptyHex));
  PT_CHECK_EQ(sha256_hex("abc"), std::string(kAbcHex));
  PT_CHECK_EQ(sha256_hex(kMessage448), std::string(kMessage448Hex));
  PT_CHECK_EQ(sha256_hex(kMessage896), std::string(kMessage896Hex));

  // The same vectors through the streaming interface, byte at a time.
  Sha256 hasher;
  hasher.update("abc");
  PT_CHECK_EQ(hex_of(hasher.finish()), std::string(kAbcHex));

  hasher.reset();
  for (const char character : kMessage448) {
    hasher.update_byte(static_cast<std::uint8_t>(character));
  }
  PT_CHECK_EQ(hex_of(hasher.finish()), std::string(kMessage448Hex));

  // to_hex of the raw digest bytes is the same rendering.
  const Digest digest = digest_bytes("abc");
  PT_CHECK_EQ(digest.to_hex(), std::string(kAbcHex));
  PT_CHECK_EQ(to_hex(std::string_view(reinterpret_cast<const char*>(digest.bytes().data()), digest.bytes().size())),
              std::string(kAbcHex));
}

PT_TEST(digest, million_a_vector_is_built_by_chunked_updates) {
  const std::string million_a(1000000, 'a');

  // One-shot.
  PT_CHECK_EQ(sha256_hex(million_a), std::string(kMillionAHex));

  // Streamed in the documented chunk sizes.
  const std::size_t chunks[] = {1, 63, 64, 65, 1000};
  for (const std::size_t chunk : chunks) {
    PT_CHECK_EQ(sha256_hex_chunked(million_a, chunk), std::string(kMillionAHex));
  }

  // A single update() of the whole buffer is the same digest again.
  Sha256 hasher;
  hasher.update(million_a);
  PT_CHECK_EQ(hex_of(hasher.finish()), std::string(kMillionAHex));

  // reset() returns the object to its initial state.
  hasher.reset();
  hasher.update(million_a);
  PT_CHECK_EQ(hex_of(hasher.finish()), std::string(kMillionAHex));
}

PT_TEST(digest, streaming_equals_one_shot_for_every_chunk_boundary) {
  const std::vector<std::string> messages = {std::string(), std::string("abc"), std::string("a"), kMessage448,
                                             kMessage896, std::string(55, 'x'), std::string(56, 'x'),
                                             std::string(63, 'x'), std::string(64, 'x'), std::string(65, 'x'),
                                             std::string(119, 'x'), std::string(120, 'x'), std::string(127, 'x'),
                                             std::string(128, 'x'), std::string(129, 'x')};
  const std::size_t chunks[] = {1, 63, 64, 65};
  for (const std::string& message : messages) {
    const std::string expected = sha256_hex(message);
    for (const std::size_t chunk : chunks) {
      PT_CHECK_EQ(sha256_hex_chunked(message, chunk), expected);
    }
    // Two updates that split the message at an arbitrary interior point agree.
    if (message.size() >= 2) {
      Sha256 split;
      const std::size_t cut = message.size() / 2;
      split.update(std::string_view(message).substr(0, cut));
      split.update(std::string_view(message).substr(cut));
      PT_CHECK_EQ(hex_of(split.finish()), expected);
    }
    // An empty update between two real ones changes nothing.
    if (message.size() >= 2) {
      Sha256 padded;
      const std::size_t cut = message.size() - 1;
      padded.update(std::string_view(message).substr(0, cut));
      padded.update(std::string_view());
      padded.update(std::string_view(message).substr(cut));
      PT_CHECK_EQ(hex_of(padded.finish()), expected);
    }
  }
}

// ===========================================================================
// Digest::parse_hex / to_hex / is_zero
// ===========================================================================

PT_TEST(digest, parse_hex_requires_exactly_sixty_four_lowercase_hex_characters) {
  const std::string valid(kAbcHex);
  PT_CHECK_EQ(valid.size(), std::size_t{64});
  const auto parsed = Digest::parse_hex(valid);
  PT_REQUIRE(parsed.has_value());
  PT_CHECK_EQ(parsed.value().to_hex(), valid);

  // Every prefix length below 64 and every extension above 64 is refused.
  for (std::size_t length = 0; length < 64; ++length) {
    PT_CHECK_ERROR(Digest::parse_hex(valid.substr(0, length)), ErrorCode::MalformedRecord);
  }
  for (std::size_t extra = 1; extra <= 4; ++extra) {
    PT_CHECK_ERROR(Digest::parse_hex(valid + std::string(extra, '0')), ErrorCode::MalformedRecord);
  }
  PT_CHECK_ERROR(Digest::parse_hex(""), ErrorCode::MalformedRecord);

  // Uppercase hex is not the canonical form.
  std::string upper = valid;
  upper[0] = 'B';
  upper[63] = 'D';
  PT_CHECK_ERROR(Digest::parse_hex(upper), ErrorCode::MalformedRecord);
  PT_CHECK_ERROR(Digest::parse_hex(std::string(64, 'A')), ErrorCode::MalformedRecord);

  // Non-hex characters are refused wherever they appear.
  PT_CHECK_ERROR(Digest::parse_hex(std::string(64, 'g')), ErrorCode::MalformedRecord);
  PT_CHECK_ERROR(Digest::parse_hex(std::string(64, ' ')), ErrorCode::MalformedRecord);
  PT_CHECK_ERROR(Digest::parse_hex(std::string(64, '0') + "\n"), ErrorCode::MalformedRecord);
  PT_CHECK_ERROR(Digest::parse_hex("0x" + valid.substr(2)), ErrorCode::MalformedRecord);
  PT_CHECK_ERROR(Digest::parse_hex(valid.substr(0, 63) + "-"), ErrorCode::MalformedRecord);
}

PT_TEST(digest, parse_hex_to_hex_round_trip_and_zero) {
  const std::string all_zero(64, '0');
  const auto zero = Digest::parse_hex(all_zero);
  PT_REQUIRE(zero.has_value());
  PT_CHECK(zero.value().is_zero());
  PT_CHECK_EQ(zero.value().bytes().size(), std::size_t{32});
  for (const std::uint8_t byte : zero.value().bytes()) {
    PT_CHECK_EQ(static_cast<unsigned>(byte), 0u);
  }

  const std::string all_ff(64, 'f');
  const auto filled = Digest::parse_hex(all_ff);
  PT_REQUIRE(filled.has_value());
  PT_CHECK_FALSE(filled.value().is_zero());
  PT_CHECK_EQ(filled.value().to_hex(), all_ff);
  for (const std::uint8_t byte : filled.value().bytes()) {
    PT_CHECK_EQ(static_cast<unsigned>(byte), 0xFFu);
  }

  // A single non-zero bit anywhere makes the digest non-zero.
  for (std::size_t index = 0; index < 64; ++index) {
    std::string spelling = all_zero;
    spelling[index] = '1';
    const auto candidate = Digest::parse_hex(spelling);
    PT_REQUIRE(candidate.has_value());
    PT_CHECK_FALSE(candidate.value().is_zero());
    PT_CHECK_EQ(candidate.value().to_hex(), spelling);
  }

  // Round trip of a real digest, and default construction is the zero digest.
  const Digest real = digest_bytes("power-topology");
  const auto reparsed = Digest::parse_hex(real.to_hex());
  PT_REQUIRE(reparsed.has_value());
  PT_CHECK(reparsed.value() == real);
  PT_CHECK_FALSE(real.is_zero());
  const Digest zero_default;
  PT_CHECK(zero_default.is_zero());
  PT_CHECK(zero_default == zero.value());
}

// ===========================================================================
// Sensitivity and endianness
// ===========================================================================

PT_TEST(digest, digest_is_sensitive_to_every_single_bit_flip) {
  const std::string base = "0123456789abcdefghijklmnopqrstuv";  // exactly 32 bytes
  PT_CHECK_EQ(base.size(), std::size_t{32});
  const Digest reference = digest_bytes(base);

  for (std::size_t index = 0; index < base.size(); ++index) {
    for (unsigned bit = 0; bit < 8; ++bit) {
      const auto mask = static_cast<unsigned char>(1u << bit);
      const std::string mutated = bit_flipped(base, index, mask);
      PT_CHECK(mutated != base);
      PT_CHECK_FALSE(digest_bytes(mutated) == reference);
    }
  }

  // The same message in a different length is a different digest as well.
  PT_CHECK_FALSE(digest_bytes(base.substr(0, 31)) == reference);
  PT_CHECK_FALSE(digest_bytes(base + "v") == reference);
  PT_CHECK(digest_bytes(base) == reference);
}

PT_TEST(digest, update_u32_is_little_and_big_endian_as_documented) {
  const std::uint32_t value = 0x01020304u;
  const std::string little = bytes({0x04, 0x03, 0x02, 0x01});
  const std::string big = bytes({0x01, 0x02, 0x03, 0x04});

  Sha256 little_hasher;
  little_hasher.update_u32(true, value);
  Sha256 big_hasher;
  big_hasher.update_u32(false, value);
  Sha256 little_bytes;
  little_bytes.update(little);
  Sha256 big_bytes;
  big_bytes.update(big);

  PT_CHECK(hex_of(little_hasher.finish()) == hex_of(little_bytes.finish()));
  PT_CHECK(hex_of(big_hasher.finish()) == hex_of(big_bytes.finish()));
  PT_CHECK_FALSE(hex_of(little_bytes.finish()) == hex_of(big_bytes.finish()));

  // Zero and the maximum value behave like their byte sequences too.
  Sha256 zero_value;
  zero_value.update_u32(true, 0u);
  Sha256 zero_bytes;
  zero_bytes.update(bytes({0x00, 0x00, 0x00, 0x00}));
  PT_CHECK(hex_of(zero_value.finish()) == hex_of(zero_bytes.finish()));

  Sha256 max_hasher;
  max_hasher.update_u32(true, 0xFFFFFFFFu);
  Sha256 max_bytes;
  max_bytes.update(bytes({0xFF, 0xFF, 0xFF, 0xFF}));
  PT_CHECK(hex_of(max_hasher.finish()) == hex_of(max_bytes.finish()));
}

PT_TEST(digest, update_u64_is_little_and_big_endian_as_documented) {
  const std::uint64_t value = 0x0102030405060708ull;
  const std::string little = bytes({0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01});
  const std::string big = bytes({0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08});

  Sha256 little_hasher;
  little_hasher.update_u64(true, value);
  Sha256 big_hasher;
  big_hasher.update_u64(false, value);
  Sha256 little_bytes;
  little_bytes.update(little);
  Sha256 big_bytes;
  big_bytes.update(big);

  PT_CHECK(hex_of(little_hasher.finish()) == hex_of(little_bytes.finish()));
  PT_CHECK(hex_of(big_hasher.finish()) == hex_of(big_bytes.finish()));
  PT_CHECK_FALSE(hex_of(little_bytes.finish()) == hex_of(big_bytes.finish()));

  Sha256 max_hasher;
  max_hasher.update_u64(false, 0xFFFFFFFFFFFFFFFFull);
  Sha256 max_bytes;
  max_bytes.update(std::string(8, static_cast<char>(0xFF)));
  PT_CHECK(hex_of(max_hasher.finish()) == hex_of(max_bytes.finish()));
}

PT_TEST(digest, scalar_updates_compose_like_their_byte_sequences) {
  // A stream mixing scalars and raw bytes equals the concatenated byte stream,
  // including when the pieces cross a 64-byte block boundary.
  std::string expected_bytes;
  Sha256 streamed;
  for (unsigned index = 0; index < 40; ++index) {
    const std::uint32_t first = 0xAABB0000u + index;
    const std::uint64_t second = 0x0102030405060708ull + index;
    streamed.update_u32(false, first);
    streamed.update_u64(true, second);
    expected_bytes.append(bytes({static_cast<unsigned>((first >> 24) & 0xFFu), static_cast<unsigned>((first >> 16) & 0xFFu),
                                 static_cast<unsigned>((first >> 8) & 0xFFu), static_cast<unsigned>(first & 0xFFu)}));
    for (unsigned shift = 0; shift < 8; ++shift) {
      expected_bytes.push_back(static_cast<char>(static_cast<unsigned char>((second >> (shift * 8)) & 0xFFu)));
    }
  }
  Sha256 expected_hasher;
  expected_hasher.update(expected_bytes);
  PT_CHECK(hex_of(streamed.finish()) == hex_of(expected_hasher.finish()));
}

PT_TEST(digest, digest_values_compare_and_order_deterministically) {
  const auto low = Digest::parse_hex(std::string(64, '0'));
  const auto one = Digest::parse_hex(std::string(63, '0') + "1");
  const auto high = Digest::parse_hex(std::string(64, 'f'));
  PT_REQUIRE(low.has_value());
  PT_REQUIRE(one.has_value());
  PT_REQUIRE(high.has_value());
  PT_CHECK(low.value() < one.value());
  PT_CHECK(one.value() < high.value());
  PT_CHECK(high.value() > low.value());
  PT_CHECK(low.value() != one.value());
  PT_CHECK(low.value() == low.value());

  // digest_bytes of the empty input is the published empty-message digest and
  // is distinct from the all-zero digest.
  const Digest empty = digest_bytes("");
  PT_CHECK_EQ(empty.to_hex(), std::string(kEmptyHex));
  PT_CHECK_FALSE(empty.is_zero());
  PT_CHECK_FALSE(empty == low.value());
}
