// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Summon Software Labs.
//
// Import grammar ("ptg") tests.
//
// The reference document below is a complete, structurally valid generation:
// every node kind, a containment generated by the "in=" shorthand, an alias, a
// redundancy group with failure-domain references and an exclusivity
// constraint. Parsing rejects are asserted with their documented stable error
// code, never with "it failed".

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "test_framework.hpp"

#include "dccp/power_topology/import.hpp"
#include "dccp/power_topology/limits.hpp"
#include "dccp/power_topology/model.hpp"
#include "dccp/power_topology/result.hpp"
#include "dccp/power_topology/topology.hpp"

namespace {

using namespace dccp::power_topology;

// ---------------------------------------------------------------------------
// Documents
// ---------------------------------------------------------------------------

/// 26 physical lines followed by a final newline. Every physical line counts,
/// including blank lines and comment lines, and the empty line that follows the
/// last newline is counted too, so ImportStats::lines is 27.
std::string reference_document() {
  return
      "# reference import document\n"
      "\n"
      "facility facility:dc-1@7\n"
      "provenance producer=ptg-tests origin=imported witness=\"reference fixture\" "
      "source=registry:upstream@3 authority-epoch=42\n"
      "\n"
      "node util utility_feed class=primary voltage=medium_voltage name=\"Utility feed\"\n"
      "node sw switchgear kind=main_switchboard voltage=medium_voltage ref=location:row-1\n"
      "node xfmr transformer primary=medium_voltage secondary=low_voltage winding=delta_wye\n"
      "node pdu pdu kind=rack voltage=low_voltage in=sw\n"
      "node c1 circuit kind=branch voltage=low_voltage in=sw\n"
      "node c2 circuit kind=branch voltage=low_voltage in=sw\n"
      "node lap load_attachment_point attachment=dual_corded consumer=consumer:rack-7\n"
      "\n"
      "edge e1 feeds util.source -> sw.input\n"
      "edge e2 feeds sw.output -> xfmr.primary\n"
      "edge e3 feeds xfmr.secondary -> pdu.input_a\n"
      "edge e4 feeds pdu.output -> c1.line\n"
      "edge e5 feeds c1.load -> lap.attachment\n"
      "edge e6 feeds pdu.output -> c2.line\n"
      "edge e7 feeds c2.load -> lap.attachment\n"
      "\n"
      "alias sw-legacy sw\n"
      "\n"
      "group g1 scheme=two_n name=\"dual cord\" require-distinct-failure-domains "
      "c1:failure_domain:fd-a c2:failure_domain:fd-b\n"
      "\n"
      "exclusive x1 max=1 pdu.input_a pdu.input_b\n";
}

/// A minimal skeleton: the facility line is required, so every rejection case
/// is expressed as a facility line plus the offending line, which is line 2.
std::string document_with(std::string body) { return "facility facility:dc-1@7\n" + std::move(body); }

const Node* find_draft_node(const TopologyDraft& draft, std::string_view id) {
  for (const Node& node : draft.nodes) {
    if (node.id.value() == id) {
      return &node;
    }
  }
  return nullptr;
}

const Edge* find_draft_edge(const TopologyDraft& draft, std::string_view id) {
  for (const Edge& edge : draft.edges) {
    if (edge.id.value() == id) {
      return &edge;
    }
  }
  return nullptr;
}

// ---------------------------------------------------------------------------
// Assertions
// ---------------------------------------------------------------------------

void expect_parse_error(std::string_view text, ErrorCode expected, std::string_view expected_subject, const char* file,
                        int line) {
  const Result<TopologyDraft> parsed = parse_import(text);
  if (parsed.has_value()) {
    ::ptest::fail(file, line, std::string("parse_import() accepted a document that should fail with ") +
                                  std::string(error_code_name(expected)));
    return;
  }
  if (parsed.error().code() != expected) {
    ::ptest::fail(file, line, std::string("expected ") + std::string(error_code_name(expected)) + " but got " +
                                  parsed.error().to_string());
    return;
  }
  if (!expected_subject.empty() && parsed.error().subject() != expected_subject) {
    ::ptest::fail(file, line, std::string("expected subject [") + std::string(expected_subject) + "] but got [" +
                                  parsed.error().subject() + "]");
  }
}

#define EXPECT_PARSE_ERROR(text, code, subject) expect_parse_error((text), (code), (subject), __FILE__, __LINE__)

// ---------------------------------------------------------------------------
// The reference document
// ---------------------------------------------------------------------------

PT_TEST(import, reference_document_parses) {
  ImportStats stats;
  const Result<TopologyDraft> parsed = parse_import(reference_document(), &stats);
  PT_REQUIRE_OK(parsed);
  const TopologyDraft& draft = parsed.value();

  PT_CHECK_EQ(stats.lines, std::size_t{27});
  PT_CHECK_EQ(stats.nodes, std::size_t{7});
  // ImportStats::edges counts the explicit "edge" lines; the three containment
  // edges generated by the "in=" shorthand are reported in the draft instead.
  PT_CHECK_EQ(stats.edges, std::size_t{7});
  PT_CHECK_EQ(stats.groups, std::size_t{1});
  PT_CHECK_EQ(stats.aliases, std::size_t{1});
  PT_CHECK_EQ(stats.constraints, std::size_t{1});

  PT_CHECK_EQ(draft.nodes.size(), std::size_t{7});
  PT_CHECK_EQ(draft.edges.size(), std::size_t{10});
  PT_CHECK_EQ(draft.aliases.size(), std::size_t{1});
  PT_CHECK_EQ(draft.groups.size(), std::size_t{1});
  PT_CHECK_EQ(draft.constraints.size(), std::size_t{1});

  // Facility and provenance.
  PT_CHECK(draft.facility.kind == ExternalRefKind::Facility);
  PT_CHECK_EQ(draft.facility.identity, std::string("dc-1"));
  PT_CHECK_EQ(draft.facility.generation.value(), static_cast<std::uint64_t>(7));
  PT_CHECK_EQ(draft.provenance.producer, std::string("ptg-tests"));
  PT_CHECK(draft.provenance.origin == ProvenanceOrigin::Imported);
  PT_CHECK_EQ(draft.provenance.witness, std::string("reference fixture"));
  PT_REQUIRE(draft.provenance.source_reference.has_value());
  PT_CHECK(draft.provenance.source_reference->kind == ExternalRefKind::Registry);
  PT_CHECK_EQ(draft.provenance.source_reference->identity, std::string("upstream"));
  PT_CHECK_EQ(draft.provenance.source_reference->generation.value(), static_cast<std::uint64_t>(3));
  PT_CHECK_EQ(draft.provenance.authority_epoch.value(), static_cast<std::uint64_t>(42));

  // Every node kind and every declared attribute value.
  const Node* util = find_draft_node(draft, "util");
  PT_REQUIRE(util != nullptr);
  PT_CHECK(util->kind() == NodeKind::UtilityFeed);
  PT_REQUIRE(util->as_utility_feed() != nullptr);
  PT_CHECK(util->as_utility_feed()->feed_class == FeedClass::Primary);
  PT_REQUIRE(util->as_utility_feed()->nominal_voltage.has_value());
  PT_CHECK(util->as_utility_feed()->nominal_voltage.value() == VoltageClass::MediumVoltage);
  PT_CHECK_EQ(util->display_name, std::string("Utility feed"));

  const Node* sw = find_draft_node(draft, "sw");
  PT_REQUIRE(sw != nullptr);
  PT_CHECK(sw->kind() == NodeKind::Switchgear);
  PT_REQUIRE(sw->as_switchgear() != nullptr);
  PT_CHECK(sw->as_switchgear()->kind == SwitchgearKind::MainSwitchboard);
  PT_CHECK(sw->as_switchgear()->voltage == VoltageClass::MediumVoltage);
  PT_REQUIRE(sw->references.size() == 1u);
  PT_CHECK(sw->references.front().kind == ExternalRefKind::Location);
  PT_CHECK_EQ(sw->references.front().identity, std::string("row-1"));

  const Node* transformer = find_draft_node(draft, "xfmr");
  PT_REQUIRE(transformer != nullptr);
  PT_CHECK(transformer->kind() == NodeKind::Transformer);
  PT_REQUIRE(transformer->as_transformer() != nullptr);
  PT_CHECK(transformer->as_transformer()->primary_class == VoltageClass::MediumVoltage);
  PT_CHECK(transformer->as_transformer()->secondary_class == VoltageClass::LowVoltage);
  PT_CHECK(!transformer->as_transformer()->tertiary_class.has_value());
  PT_REQUIRE(transformer->as_transformer()->winding.has_value());
  PT_CHECK(transformer->as_transformer()->winding.value() == WindingConfiguration::DeltaWye);

  const Node* pdu = find_draft_node(draft, "pdu");
  PT_REQUIRE(pdu != nullptr);
  PT_CHECK(pdu->kind() == NodeKind::Pdu);
  PT_CHECK(pdu->as_pdu()->kind == PduKind::Rack);
  PT_CHECK(pdu->as_pdu()->voltage == VoltageClass::LowVoltage);

  const Node* circuit = find_draft_node(draft, "c1");
  PT_REQUIRE(circuit != nullptr);
  PT_CHECK(circuit->kind() == NodeKind::Circuit);
  PT_CHECK(circuit->as_circuit()->kind == CircuitKind::Branch);
  PT_REQUIRE(circuit->as_circuit()->voltage.has_value());
  PT_CHECK(circuit->as_circuit()->voltage.value() == VoltageClass::LowVoltage);

  const Node* attachment = find_draft_node(draft, "lap");
  PT_REQUIRE(attachment != nullptr);
  PT_CHECK(attachment->kind() == NodeKind::LoadAttachmentPoint);
  PT_REQUIRE(attachment->as_load_attachment_point() != nullptr);
  PT_CHECK(attachment->as_load_attachment_point()->attachment == AttachmentKind::DualCorded);
  PT_CHECK(attachment->as_load_attachment_point()->consumer.kind == ExternalRefKind::Consumer);
  PT_CHECK_EQ(attachment->as_load_attachment_point()->consumer.identity, std::string("rack-7"));

  // The "in=" shorthand emits a deterministic containment edge.
  const Edge* contains_pdu = find_draft_edge(draft, "contains:sw:pdu");
  PT_REQUIRE(contains_pdu != nullptr);
  PT_CHECK(contains_pdu->kind == EdgeKind::Contains);
  PT_CHECK_EQ(contains_pdu->from.node.value(), std::string("sw"));
  PT_CHECK(contains_pdu->from.port == PortRole::Enclosure);
  PT_CHECK_EQ(contains_pdu->to.node.value(), std::string("pdu"));
  PT_CHECK(contains_pdu->to.port == PortRole::Enclosed);
  const Edge* contains_c1 = find_draft_edge(draft, "contains:sw:c1");
  const Edge* contains_c2 = find_draft_edge(draft, "contains:sw:c2");
  PT_REQUIRE(contains_c1 != nullptr && contains_c2 != nullptr);
  PT_CHECK_EQ(contains_c1->to.node.value(), std::string("c1"));
  PT_CHECK_EQ(contains_c2->to.node.value(), std::string("c2"));

  // Aliases and groups.
  PT_CHECK_EQ(draft.aliases.front().id.value(), std::string("sw-legacy"));
  PT_CHECK_EQ(draft.aliases.front().target.value(), std::string("sw"));

  const RedundancyGroup& group = draft.groups.front();
  PT_CHECK_EQ(group.id.value(), std::string("g1"));
  PT_CHECK(group.scheme == RedundancyScheme::TwoN);
  PT_CHECK_EQ(group.display_name, std::string("dual cord"));
  PT_CHECK(group.require_distinct_failure_domains);
  PT_CHECK(!group.require_independent_paths);
  PT_REQUIRE(group.members.size() == 2u);
  PT_CHECK_EQ(group.members[0].declared, std::string("c1"));
  PT_CHECK_EQ(group.members[1].declared, std::string("c2"));
  PT_REQUIRE(group.members[0].failure_domain.has_value());
  PT_REQUIRE(group.members[1].failure_domain.has_value());
  PT_CHECK(group.members[0].failure_domain->kind == ExternalRefKind::FailureDomain);
  PT_CHECK_EQ(group.members[0].failure_domain->identity, std::string("fd-a"));
  PT_CHECK_EQ(group.members[1].failure_domain->identity, std::string("fd-b"));

  const ExclusivityConstraint& constraint = draft.constraints.front();
  PT_CHECK_EQ(constraint.id.value(), std::string("x1"));
  PT_CHECK_EQ(constraint.max_energized, static_cast<std::uint32_t>(1));
  PT_REQUIRE(constraint.members.size() == 2u);
  PT_CHECK_EQ(constraint.members[0].node.value(), std::string("pdu"));
  PT_CHECK(constraint.members[0].port == PortRole::InputA);
  PT_CHECK(constraint.members[1].port == PortRole::InputB);

  // The parsed document is a valid generation, and validates cleanly.
  PT_CHECK(Topology::validate_draft(draft).valid());
  PT_REQUIRE_OK(Topology::create_first(draft));
}

PT_TEST(import, exported_document_reparses_to_the_same_generation) {
  const Result<TopologyDraft> parsed = parse_import(reference_document());
  PT_REQUIRE_OK(parsed);
  const Result<Topology> original = Topology::create_first(parsed.value());
  PT_REQUIRE_OK(original);

  const std::string exported = export_import(original.value());
  ImportStats exported_stats;
  const Result<TopologyDraft> reparsed = parse_import(exported, &exported_stats);
  PT_REQUIRE_OK(reparsed);
  PT_CHECK(Topology::validate_draft(reparsed.value()).valid());
  const Result<Topology> round_tripped = Topology::create_first(reparsed.value());
  PT_REQUIRE_OK(round_tripped);

  // The round-trip obligation: same canonical digest.
  PT_CHECK_EQ(round_tripped.value().digest(), original.value().digest());
  PT_CHECK_EQ(round_tripped.value().canonical_bytes().value(), original.value().canonical_bytes().value());
  PT_CHECK_EQ(reparsed.value().nodes.size(), parsed.value().nodes.size());
  PT_CHECK_EQ(reparsed.value().edges.size(), parsed.value().edges.size());
  PT_CHECK_EQ(reparsed.value().aliases.size(), parsed.value().aliases.size());
  PT_CHECK_EQ(reparsed.value().groups.size(), parsed.value().groups.size());
  PT_CHECK_EQ(reparsed.value().constraints.size(), parsed.value().constraints.size());
  // Exporting twice is deterministic.
  PT_CHECK_EQ(export_import(round_tripped.value()), exported);
}

// ---------------------------------------------------------------------------
// Parsing rejects
// ---------------------------------------------------------------------------

PT_TEST(import, rejects_unknown_command) {
  EXPECT_PARSE_ERROR(document_with("bogus x\n"), ErrorCode::UnknownEnumToken, "line 2 command=bogus");
}

PT_TEST(import, rejects_unknown_key) {
  EXPECT_PARSE_ERROR(document_with("node n1 switchgear kind=main_switchboard voltage=low_voltage bogus=1\n"),
                     ErrorCode::UnknownEnumToken, "line 2 key=bogus");
  // A key that belongs to another node kind is equally unknown here.
  EXPECT_PARSE_ERROR(document_with("node n1 bus class=primary kind=main voltage=low_voltage\n"),
                     ErrorCode::UnknownEnumToken, "line 2 key=class");
}

PT_TEST(import, rejects_duplicate_key) {
  EXPECT_PARSE_ERROR(document_with("node n1 switchgear kind=main_switchboard voltage=low_voltage kind=panelboard\n"),
                     ErrorCode::DuplicateField, "line 2 key=kind");
  EXPECT_PARSE_ERROR(document_with("node n1 utility_feed class=primary class=secondary\n"),
                     ErrorCode::DuplicateField, "line 2 key=class");
}

PT_TEST(import, rejects_missing_facility) {
  EXPECT_PARSE_ERROR("node n1 bus kind=main voltage=low_voltage\n", ErrorCode::MissingField, "");
  EXPECT_PARSE_ERROR("# only a comment\n", ErrorCode::MissingField, "");
  EXPECT_PARSE_ERROR(std::string(), ErrorCode::MissingField, "");
}

PT_TEST(import, rejects_second_facility_line) {
  EXPECT_PARSE_ERROR("facility facility:dc-1@7\nfacility facility:dc-2@8\n", ErrorCode::DuplicateField, "line 2");
}

PT_TEST(import, rejects_second_provenance_line) {
  EXPECT_PARSE_ERROR(
      document_with("provenance producer=a origin=authored\nprovenance producer=b origin=authored\n"),
      ErrorCode::DuplicateField, "line 3");
}

PT_TEST(import, rejects_malformed_endpoint) {
  // No port at all.
  EXPECT_PARSE_ERROR(document_with("edge e1 feeds n1 -> n2.input\n"), ErrorCode::MalformedRecord, "line 2");
  // Empty port.
  EXPECT_PARSE_ERROR(document_with("edge e1 feeds n1. -> n2.input\n"), ErrorCode::MalformedRecord, "line 2");
  // A parser-level endpoint fault, not only a validation-level one.
  const Result<TopologyDraft> parsed = parse_import(document_with("edge e1 feeds n1 -> n2.input\n"));
  PT_REQUIRE(!parsed.has_value());
  PT_CHECK_EQ(parsed.error().code(), ErrorCode::MalformedRecord);
}

PT_TEST(import, rejects_unterminated_quote) {
  // A quoted segment that is never closed. The document-level quote balance is
  // checked before any command is interpreted, so the refusal is a
  // MalformedRecord attributed to the offending line.
  EXPECT_PARSE_ERROR(document_with("node n1 switchgear kind=main_switchboard voltage=low_voltage name=\"abc\n"),
                     ErrorCode::MalformedRecord, "line 2");
  EXPECT_PARSE_ERROR(document_with("node n1 switchgear kind=main_switchboard voltage=low_voltage name=\"abc def\n"),
                     ErrorCode::MalformedRecord, "line 2");
  // A closed quote followed by a trailing unterminated one is unbalanced too.
  EXPECT_PARSE_ERROR(document_with("node n1 switchgear kind=main_switchboard voltage=low_voltage name=\"a\" b\"\n"),
                     ErrorCode::MalformedRecord, "line 2");
}

PT_TEST(import, rejects_unbalanced_quote) {
  EXPECT_PARSE_ERROR(document_with("node n1 switchgear kind=main_switchboard voltage=low_voltage name=max\"well\n"),
                     ErrorCode::MalformedRecord, "line 2");
  EXPECT_PARSE_ERROR(document_with("node n1 switchgear kind=main_switchboard voltage=low_voltage name=\"opened\n"),
                     ErrorCode::MalformedRecord, "line 2");
  EXPECT_PARSE_ERROR(document_with("node n1 switchgear kind=main_switchboard voltage=low_voltage name=\"a\"b\"\n"),
                     ErrorCode::MalformedRecord, "line 2");
}

PT_TEST(import, rejects_token_beyond_a_bound) {
  // A display name past the documented display-text bound.
  std::string name(limits::kMaxDisplayNameBytes + 1, 'x');
  EXPECT_PARSE_ERROR(document_with("node n1 switchgear kind=main_switchboard voltage=low_voltage name=" + name + "\n"),
                     ErrorCode::TextTooLong, "");
  // A consumer identity past the external-identity bound.
  std::string identity(limits::kMaxExternalIdentityBytes + 1, 'y');
  EXPECT_PARSE_ERROR(document_with("node n1 load_attachment_point attachment=single_corded consumer=" + identity + "\n"),
                     ErrorCode::TextTooLong, "");
  // An additional external reference past the same bound.
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage ref=" + identity + "\n"),
                     ErrorCode::TextTooLong, "");
  // The bound itself is still accepted.
  const std::string at_bound(limits::kMaxExternalIdentityBytes, 'y');
  PT_REQUIRE_OK(parse_import(document_with("node n1 bus kind=main voltage=low_voltage ref=" + at_bound + "\n")));
}

PT_TEST(import, rejects_unknown_port_token) {
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\nedge e1 feeds n1.bogus -> n1.input\n"),
                     ErrorCode::UnknownEnumToken, "");
}

PT_TEST(import, rejects_unknown_node_kind) {
  EXPECT_PARSE_ERROR(document_with("node n1 bogus\n"), ErrorCode::UnknownEnumToken, "");
  EXPECT_PARSE_ERROR(document_with("node n1\n"), ErrorCode::MissingField, "line 2");
  EXPECT_PARSE_ERROR(document_with("node\n"), ErrorCode::MissingField, "line 2");
}

PT_TEST(import, rejects_unknown_enum_values_for_known_keys) {
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=bogus voltage=low_voltage\n"), ErrorCode::UnknownEnumToken, "");
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=bogus\n"), ErrorCode::UnknownEnumToken, "");
  EXPECT_PARSE_ERROR(document_with("node n1 switchgear kind=main_switchboard voltage=low_voltage\n"
                                   "group g1 scheme=bogus n1\n"),
                     ErrorCode::UnknownEnumToken, "bogus");
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\n"
                                   "edge e1 bogus n1.input -> n1.output\n"),
                     ErrorCode::UnknownEnumToken, "");
}

PT_TEST(import, rejects_malformed_number) {
  EXPECT_PARSE_ERROR(document_with("provenance producer=p origin=authored authority-epoch=abc\n"),
                     ErrorCode::MalformedNumber, "line 2");
  EXPECT_PARSE_ERROR(document_with("provenance producer=p origin=authored authority-epoch=-1\n"),
                     ErrorCode::MalformedNumber, "line 2");
  EXPECT_PARSE_ERROR(document_with("provenance producer=p origin=authored authority-epoch=99999999999999999999999\n"),
                     ErrorCode::MalformedNumber, "line 2");
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\n"
                                   "exclusive x1 max=abc n1.tie n1.input\n"),
                     ErrorCode::MalformedNumber, "line 3");
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\n"
                                   "exclusive x1 max=-1 n1.tie n1.input\n"),
                     ErrorCode::MalformedNumber, "line 3");
  // A well-formed but unrepresentable maximum is a limit, not a number fault.
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\n"
                                   "exclusive x1 max=99999999999 n1.tie n1.input\n"),
                     ErrorCode::LimitExceeded, "line 3");
}

PT_TEST(import, rejects_edge_line_with_the_wrong_token_count) {
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\n"
                                   "edge e1 feeds n1.input -> n1.input extra\n"),
                     ErrorCode::MalformedRecord, "line 3");
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\n"
                                   "edge e1 feeds n1.input n1.input\n"),
                     ErrorCode::MalformedRecord, "line 3");
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\n"
                                   "edge e1 feeds n1.input => n1.input\n"),
                     ErrorCode::MalformedRecord, "line 3");
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\n"
                                   "edge e1 n1.input -> n1.input\n"),
                     ErrorCode::MalformedRecord, "line 3");
}

PT_TEST(import, rejects_other_structural_commands_with_wrong_shape) {
  // facility takes exactly one external reference.
  EXPECT_PARSE_ERROR("facility\n", ErrorCode::MalformedRecord, "line 1");
  EXPECT_PARSE_ERROR("facility a b\n", ErrorCode::MalformedRecord, "line 1");
  // Provenance fields must be key=value.
  EXPECT_PARSE_ERROR(document_with("provenance producer\n"), ErrorCode::MalformedRecord, "line 2");
  EXPECT_PARSE_ERROR(document_with("provenance bogus=1\n"), ErrorCode::UnknownEnumToken, "line 2 key=bogus");
  EXPECT_PARSE_ERROR(document_with("provenance origin=bogus\n"), ErrorCode::UnknownEnumToken, "");
  EXPECT_PARSE_ERROR(document_with("provenance producer=p source=registry:bad@nope\n"),
                     ErrorCode::MalformedNumber, "line 2");
  // Node attributes must be key=value.
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage nokey\n"),
                     ErrorCode::MalformedRecord, "line 2");
  // Alias arity.
  EXPECT_PARSE_ERROR(document_with("alias a1\n"), ErrorCode::MalformedRecord, "line 2");
  EXPECT_PARSE_ERROR(document_with("alias a1 b c\n"), ErrorCode::MalformedRecord, "line 2");
  // A load attachment point without a consumer is missing a required field.
  EXPECT_PARSE_ERROR(document_with("node n1 load_attachment_point attachment=single_corded\n"),
                     ErrorCode::MissingField, "line 2");
  // A node identity that does not match the identifier grammar.
  EXPECT_PARSE_ERROR(document_with("node bad/name bus kind=main voltage=low_voltage\n"),
                     ErrorCode::MalformedIdentifier, "bad/name");
  // Group arity and keys.
  EXPECT_PARSE_ERROR(document_with("group g1\n"), ErrorCode::MissingField, "line 2");
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\ngroup g1 bogus=1 n1\n"),
                     ErrorCode::UnknownEnumToken, "line 3 key=bogus");
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\ngroup g1 require-bogus n1\n"),
                     ErrorCode::UnknownEnumToken, "line 3 require-bogus");
  // Exclusivity arity.
  EXPECT_PARSE_ERROR(document_with("exclusive x1\n"), ErrorCode::MissingField, "line 2");
  EXPECT_PARSE_ERROR(document_with("node n1 bus kind=main voltage=low_voltage\nexclusive x1 n1.tie n1.input\n"),
                     ErrorCode::ExclusivityCardinality, "x1");
}

// ---------------------------------------------------------------------------
// Accepted forms
// ---------------------------------------------------------------------------

PT_TEST(import, accepts_comments_blank_lines_and_crlf) {
  const std::string document =
      "# leading comment\n"
      "\n"
      "facility facility:dc-1@7   # trailing comment\n"
      "node n1 bus kind=main voltage=low_voltage name=\"unit #7\"  # a hash inside quotes is not a comment\n"
      "   \t  \n"
      "\n";
  ImportStats stats;
  const Result<TopologyDraft> parsed = parse_import(document, &stats);
  PT_REQUIRE_OK(parsed);
  PT_CHECK_EQ(stats.nodes, std::size_t{1});
  PT_CHECK_EQ(parsed.value().facility.identity, std::string("dc-1"));
  const Node* node = find_draft_node(parsed.value(), "n1");
  PT_REQUIRE(node != nullptr);
  PT_CHECK_EQ(node->display_name, std::string("unit #7"));

  // The same document with CRLF line endings parses identically.
  std::string crlf;
  for (const char character : document) {
    if (character == '\n') {
      crlf.push_back('\r');
    }
    crlf.push_back(character);
  }
  ImportStats crlf_stats;
  const Result<TopologyDraft> crlf_parsed = parse_import(crlf, &crlf_stats);
  PT_REQUIRE_OK(crlf_parsed);
  PT_CHECK_EQ(crlf_stats.lines, stats.lines);
  PT_CHECK_EQ(crlf_stats.nodes, stats.nodes);
  PT_CHECK_EQ(crlf_parsed.value().nodes.front().display_name, std::string("unit #7"));

  // The reference document parses to the same digest with CRLF endings.
  std::string reference_crlf;
  for (const char character : reference_document()) {
    if (character == '\n') {
      reference_crlf.push_back('\r');
    }
    reference_crlf.push_back(character);
  }
  const Result<TopologyDraft> lf_draft = parse_import(reference_document());
  const Result<TopologyDraft> crlf_draft = parse_import(reference_crlf);
  PT_REQUIRE_OK(lf_draft);
  PT_REQUIRE_OK(crlf_draft);
  const Result<Topology> lf_topology = Topology::create_first(lf_draft.value());
  const Result<Topology> crlf_topology = Topology::create_first(crlf_draft.value());
  PT_REQUIRE_OK(lf_topology);
  PT_REQUIRE_OK(crlf_topology);
  PT_CHECK_EQ(crlf_topology.value().digest(), lf_topology.value().digest());
}

PT_TEST(import, accepts_quoted_values_with_escapes) {
  const std::string document =
      "facility facility:dc-1@7\n"
      "node n1 bus kind=main voltage=low_voltage name=\"dual feed\"\n"
      "node n2 bus kind=main voltage=low_voltage name=\"say \\\"hi\\\"\"\n"
      "node n3 bus kind=main voltage=low_voltage name=\"back\\\\slash\"\n"
      "node n4 bus kind=main voltage=low_voltage name=\"hex\\x2dname\"\n";
  const Result<TopologyDraft> parsed = parse_import(document);
  PT_REQUIRE_OK(parsed);
  const Node* first = find_draft_node(parsed.value(), "n1");
  const Node* second = find_draft_node(parsed.value(), "n2");
  const Node* third = find_draft_node(parsed.value(), "n3");
  const Node* fourth = find_draft_node(parsed.value(), "n4");
  PT_REQUIRE(first != nullptr && second != nullptr && third != nullptr && fourth != nullptr);
  PT_CHECK_EQ(first->display_name, std::string("dual feed"));
  PT_CHECK_EQ(second->display_name, std::string("say \"hi\""));
  PT_CHECK_EQ(third->display_name, std::string("back\\slash"));
  PT_CHECK_EQ(fourth->display_name, std::string("hex-name"));
  // The escaped values survive the canonical round trip as well.
  const Result<Topology> topology = Topology::create_first(parsed.value());
  PT_REQUIRE_OK(topology);
  const Result<Topology> decoded = Topology::decode(topology.value().canonical_bytes().value());
  PT_REQUIRE_OK(decoded);
  PT_CHECK_EQ(decoded.value().find_node(NodeId::parse("n2").value())->display_name, std::string("say \"hi\""));
}

PT_TEST(import, accepts_quoted_identity_containing_a_space) {
  const Result<TopologyDraft> quoted = parse_import("facility \"dc 1\"\n");
  PT_REQUIRE_OK(quoted);
  PT_CHECK(quoted.value().facility.kind == ExternalRefKind::Facility);
  PT_CHECK_EQ(quoted.value().facility.identity, std::string("dc 1"));
  PT_CHECK_EQ(quoted.value().facility.generation.value(), static_cast<std::uint64_t>(0));

  // A quoted identity inside a kind-qualified external reference.
  const Result<TopologyDraft> qualified =
      parse_import("facility location:\"dc 1\"@4\nnode n1 bus kind=main voltage=low_voltage ref=location:\"row 7\"\n");
  PT_REQUIRE_OK(qualified);
  PT_CHECK(qualified.value().facility.kind == ExternalRefKind::Location);
  PT_CHECK_EQ(qualified.value().facility.identity, std::string("dc 1"));
  PT_CHECK_EQ(qualified.value().facility.generation.value(), static_cast<std::uint64_t>(4));
  const Node* node = find_draft_node(qualified.value(), "n1");
  PT_REQUIRE(node != nullptr);
  PT_REQUIRE(node->references.size() == 1u);
  PT_CHECK(node->references.front().kind == ExternalRefKind::Location);
  PT_CHECK_EQ(node->references.front().identity, std::string("row 7"));
}

PT_TEST(import, accepts_unquoted_external_reference_with_kind_and_generation) {
  const Result<TopologyDraft> parsed =
      parse_import("facility facility:dc-1@9\nnode n1 bus kind=main voltage=low_voltage ref=asset:a-1@5 ref=plain\n");
  PT_REQUIRE_OK(parsed);
  PT_CHECK(parsed.value().facility.kind == ExternalRefKind::Facility);
  PT_CHECK_EQ(parsed.value().facility.identity, std::string("dc-1"));
  PT_CHECK_EQ(parsed.value().facility.generation.value(), static_cast<std::uint64_t>(9));
  const Node* node = find_draft_node(parsed.value(), "n1");
  PT_REQUIRE(node != nullptr);
  PT_REQUIRE(node->references.size() == 2u);
  PT_CHECK(node->references[0].kind == ExternalRefKind::Asset);
  PT_CHECK_EQ(node->references[0].identity, std::string("a-1"));
  PT_CHECK_EQ(node->references[0].generation.value(), static_cast<std::uint64_t>(5));
  PT_CHECK(node->references[1].kind == ExternalRefKind::Registry);
  PT_CHECK_EQ(node->references[1].identity, std::string("plain"));
  // The bytes of an external identity are preserved exactly.
  PT_CHECK_EQ(std::string(node->references[1].identity), std::string("plain"));
}

PT_TEST(import, accepts_a_repeated_ref_key_on_one_node) {
  const Result<TopologyDraft> parsed = parse_import(
      "facility facility:dc-1@7\n"
      "node n1 bus kind=main voltage=low_voltage ref=asset:a-1 ref=rack:r-2 ref=location:l-3 ref=asset:a-1\n");
  PT_REQUIRE_OK(parsed);
  const Node* node = find_draft_node(parsed.value(), "n1");
  PT_REQUIRE(node != nullptr);
  PT_REQUIRE(node->references.size() == 4u);
  PT_CHECK(node->references[0].kind == ExternalRefKind::Asset);
  PT_CHECK(node->references[1].kind == ExternalRefKind::Rack);
  PT_CHECK(node->references[2].kind == ExternalRefKind::Location);
  PT_CHECK(node->references[3].kind == ExternalRefKind::Asset);
  PT_CHECK_EQ(node->references[3].identity, std::string("a-1"));

  // One reference past the documented per-node bound is refused.
  std::string document = "facility facility:dc-1@7\nnode n1 bus kind=main voltage=low_voltage";
  for (std::size_t index = 0; index <= limits::kMaxNodeReferences; ++index) {
    document += " ref=asset:r" + std::to_string(index);
  }
  document += "\n";
  EXPECT_PARSE_ERROR(document, ErrorCode::LimitExceeded, "line 2");
}

PT_TEST(import, accepts_group_requirement_flags) {
  const std::string document =
      "facility facility:dc-1@7\n"
      "node n1 bus kind=main voltage=low_voltage\n"
      "node n2 bus kind=main voltage=low_voltage\n"
      "group g1 scheme=n_plus_one name=\"pair\" require-distinct-failure-domains require-independent-paths n1 n2\n";
  ImportStats stats;
  const Result<TopologyDraft> parsed = parse_import(document, &stats);
  PT_REQUIRE_OK(parsed);
  PT_CHECK_EQ(stats.groups, std::size_t{1});
  const RedundancyGroup& group = parsed.value().groups.front();
  PT_CHECK(group.require_distinct_failure_domains);
  PT_CHECK(group.require_independent_paths);
  PT_CHECK(group.scheme == RedundancyScheme::NPlusOne);
  PT_CHECK_EQ(group.display_name, std::string("pair"));
  PT_REQUIRE(group.members.size() == 2u);
  PT_CHECK_EQ(group.members[0].declared, std::string("n1"));
  PT_CHECK(!group.members[0].failure_domain.has_value());
  // A member may carry its failure domain inline.
  const Result<TopologyDraft> with_domain = parse_import(
      "facility facility:dc-1@7\n"
      "node n1 bus kind=main voltage=low_voltage\n"
      "node n2 bus kind=main voltage=low_voltage\n"
      "group g1 n1:failure_domain:fd-a n2:failure_domain:fd-b\n");
  PT_REQUIRE_OK(with_domain);
  const RedundancyGroup& domain_group = with_domain.value().groups.front();
  PT_REQUIRE(domain_group.members.size() == 2u);
  PT_REQUIRE(domain_group.members[1].failure_domain.has_value());
  PT_CHECK(domain_group.members[1].failure_domain->kind == ExternalRefKind::FailureDomain);
  PT_CHECK_EQ(domain_group.members[1].failure_domain->identity, std::string("fd-b"));
}

// ---------------------------------------------------------------------------
// Bounds
// ---------------------------------------------------------------------------

PT_TEST(import, rejects_document_beyond_the_byte_bound) {
  // The document bound is checked before anything is tokenized: this input is
  // also an unknown command, but the size fault is the one that is reported.
  std::string document(limits::kMaxImportBytes + 1, 'x');
  EXPECT_PARSE_ERROR(document, ErrorCode::LimitExceeded, "");
  // One byte less is inside the bound and fails later, for a different reason.
  document.resize(limits::kMaxImportBytes);
  const Result<TopologyDraft> parsed = parse_import(document);
  PT_REQUIRE(!parsed.has_value());
  PT_CHECK(parsed.error().code() == ErrorCode::UnknownEnumToken ||
           parsed.error().code() == ErrorCode::LimitExceeded);
}

PT_TEST(import, rejects_line_beyond_the_line_bound) {
  // A line past the bound is refused before it is tokenized or interpreted, so
  // the length fault is reported instead of the command fault on that line.
  const std::string long_line(limits::kMaxImportLineBytes + 1, 'x');
  EXPECT_PARSE_ERROR("facility facility:dc-1@7\n" + long_line + "\n", ErrorCode::LimitExceeded, "line 2");
  // The same applies to a comment line, which is measured before it is stripped.
  EXPECT_PARSE_ERROR("facility facility:dc-1@7\n#" + long_line + "\n", ErrorCode::LimitExceeded, "line 2");
  // A line exactly at the bound is accepted (the comment introducer counts).
  const std::string at_bound(limits::kMaxImportLineBytes - 1u, 'x');
  const Result<TopologyDraft> parsed = parse_import("facility facility:dc-1@7\n#" + at_bound + "\n");
  PT_REQUIRE_OK(parsed);
}

}  // namespace
